### ISSUE TITLE
Scheduling not used for systemd timers

### ISSUE THREAD

**Issue by abrain** [roles-ansible/ansible_role_restic#10]
The role offers `schedule_*` variables for each backup task to define the time to run the backup. However, those variables are only respected for cron jobs. Systemd timers are always set up to run once per night between 2 and 5.

https://github.com/roles-ansible/ansible_role_restic/blob/c5126af60b8fd09b159dec8a4c12acf85749accb/templates/restic.timer.j2#L4-L6

Multiple backup tasks might run at quite different times, increasing the chance of an inconsistent backup. It also forces you to run application-level backups before 2 o'clock.

(I wasn't sure if this is covered by #9, because it does not mention specifics.)

**Comment by DO1JLR** [comment]
We now support some variables for systemd timers

**Comment by lisuml** [comment]
So, how to change the oncalendar value for systemd? It's still doesn't seem to be supported...
