### ISSUE TITLE
Backing up multiple paths

### ISSUE THREAD

**Issue by johanvdw** [roles-ansible/ansible_role_restic#100]
Before diving in the code to make the necessary changes:

I would like to be able to supply different folders for a backup. This actually seems to work for the backup if I specify like this:
```
restic_backups:
  nas:
    src: "'/nas/projects /nas/homes'"
```

but it will fail for the forget phase, where restic forget would need:
`--path /nas/projects --path /nas/homes`

I guess it will also not work on any of the LVM changes which were merged recently.
I'd prefer not to have different jobs, as they may block eachother.

Ideally, I think it would be nice to support an array in src like this
```
restic_backups:
  nas:
    src: 
      - /nas/projects
      - /nas/homes
```
Just wondering if anyone else is interested and what would be the cleanest way to proceed, because the logic with stdin/path/... is already quite complicated.

**Comment by nickbroon** [comment]
Only discovered that array of sources is supported by stumbling on this issue. Would be good to mention the use an array, and/or an example in the readme docs. :-)
