### ISSUE TITLE
Rest server support?

### ISSUE THREAD

**Issue by CryptGoat** [roles-ansible/ansible_role_restic#118]
When going over the list of supported repo targets it came to my attention that restic's official rest server does not appear to be supported. Can anyone conform? Is there anything you need help with to implement this?

**Comment by DO1JLR** [comment]
It is there an I am using this ansible role with the together with the restic rest server, deployed with this role: https://github.com/donat-b/ansible-restic-rest.git

And you are right @CryptGoat, it would be great to clean up and improve the readme a little bit. So I added a example for that in #119
