### ISSUE TITLE
Feture request past_backup_cmd

### ISSUE THREAD

**Issue by nuz014** [roles-ansible/ansible_role_restic#126]
New feture request:
Same as the alredy existing pre_backup_cmd but the opposite way. A command to run after the backup is taken to clean up a database dump.

**Comment by red55** [comment]
Hi everyone,
Are any updates on this?

**Comment by Pomdre** [comment]
@red55 My merge request is open, but if you use that branch the function is working.

**Comment by nuz014** [comment]
@red55 Ther is an open pull rq from me on this. #127
Waiting for the owner of the repo to accept.
