### ISSUE TITLE
The galaxy link is broken

### ISSUE THREAD

**Issue by nuz014** [roles-ansible/ansible_role_restic#129]
Hey, 

Is seams like the galaxy link is broken? 
Is it posibole to get this role up on galaxy again?

**Comment by DO1JLR** [comment]
Hey @nuz014 

I have trouble uploading this role to the do1jlr namespace. But the role is available as https://galaxy.ansible.com/ui/standalone/roles/roles-ansible/restic/

**Comment by nuz014** [comment]
Okay, thanks
