### ISSUE TITLE
Error in readme.md?

### ISSUE THREAD

**Issue by warwick-lill** [roles-ansible/ansible_role_restic#64]
I have a new laptop, on which I installed Debian Bullseye. I needed a backup application for this system and chose restic, and I would like to install restic with ansible. Having chosen ansible_role_restic it was time for my first run of ansible-galaxy. 

The install instruction is to run ansible-galaxy install arillso.restic. But shouldn't that be do1jlr.restic?

The correct action is quite likely obvious to a seasoned traveller, but for a newbie this instruction is confusing.

**Comment by DO1JLR** [comment]
thanks @warwick-lill good catch. Thanks for telling, I will fix that right away.
